version: '3.8'

services:
  
  # home-portal
  home-portal:
    image: home-portal:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:h2:file:./h2/home-portal
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
