version: '3.8'

services:
  # nginx: reverse proxy
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
     - "./nginx.conf:/etc/nginx/nginx.conf:ro"

  # database: persistence
  db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    volumes:
     - "./initdb:/docker-entrypoint-initdb.d:ro"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_USER: home
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: home
      MYSQL_ROOT_PASSWORD: password
  
  # keycloak: OAuth2
  keycloak:
    image: "quay.io/keycloak/keycloak:23.0.3"
    restart: always
    ports:
      - "8081:8080"
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL_PROPERTIES: ?allowPublicKeyRetrieval=true
      KC_PROXY: edge
    command: [
      "start-dev",
      "--http-relative-path",
      "/auth"
    ]
    depends_on:
      db:
        condition: service_healthy
